version: '3'

services:
  nginx:
    image: "nginx:${NGINX_VERSION}"
    restart: always
    volumes:
      - nginx_conf:/etc/nginx/conf.d
    networks:
      dmz:
        ipv4_address: ${NGINX_IP}

  synapse:
    image: "docker.io/matrixdotorg/synapse:${SYNAPSE_VERSION}"
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - synapse_data:/data
    depends_on:
      - synapse_db
    networks:
      internal:

  synapse_db:
    image: "docker.io/postgres:${POSTGRES_VERSION}"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - synapse_db_data:/var/lib/postgresql/data
    networks:
      internal:

  coturn:
    image: "instrumentisto/coturn:${COTURN_VERSION}"
    restart: unless-stopped
    volumes:
      - coturn:/etc/coturn
    ports:
      - "49160-49200:49160-49200/udp"
      - "3478:3478"
      - "5349:5349"
    networks:
      dmz:
        ipv4_address: ${COTURN_VERSION}

  element:
    image: "vectorim/element-web:${ELEMENT_VERSION}"
    restart: unless-stopped
    volumes:
      - element:/app
    networks:
      dmz:
        ipv4_address: ${ELEMENT_VERSION}

volumes:
  nginx_conf:
  synapse_data:
  synapse_db_data:
  coturn:
  element:

networks:
  internal:
    driver: bridge
